//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Configuration;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

[assembly :
    SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member",
        Target =
        "NUnitForms.Recorder.Application.Properties.Settings.get_Default():NUnitForms.Recorder.Application.Properties.Settings"
        )]

namespace NUnitForms.Recorder.Application.Properties
{
    [CompilerGenerated()]
    internal sealed partial class Settings : ApplicationSettingsBase
    {
        private static Settings defaultInstance = new Settings();

        public static Settings Default
        {
            get { return defaultInstance; }
        }
    }
}